### ISSUE TITLE
Override Download/Update info...

### ISSUE THREAD

**Issue by tony971** [dh4/cen64-qt#1]
If a game is not on thegamesdb.net but Cen64-Qt thinks it found a match, it will automatically fill in the blanks. There needs to be a null option for when there is no game ID.

**Comment by dh4** [comment]
I want to reconfigure the way CEN64-Qt caches the information from TheGamesDB, and this would be a good feature to add at the same time I work on that. I'll work on it when I have some time.

What game do you have that is not found? I'm sure you know, but the absolute best way to handle this is to add the information to TheGamesDB yourself so everyone can benefit from it.

**Comment by tony971** [comment]
The game was actually a prototype Dragon Sword 64. It was never released. Cen64-Qt thinks it's Flying Dragon every time it pulls info. Since Dragon Sword 64 doesn't exist on TheGamesDB, the only (temporary) solution is to manually clear the ini file and delete the cover art after you pull info.

**Comment by dh4** [comment]
A game doesn't need to have been released for it to be submitted to TheGamesDB. For example, here's Glover 2:
http://thegamesdb.net/game/22449/

People have even submitted game hacks as well:
http://thegamesdb.net/game/18877/

I'll still address this issue and add a null option when I have some time.

**Comment by dh4** [comment]
The latest commit adds the ability to delete TheGamesDB information for certain games (and keeps the game information from updating until you force it):
https://github.com/dh4/cen64-qt/commit/3d3ba53d77b21bf316733ff830f5d2b510a2f73c
