### ISSUE TITLE
How do I configure my controller to work with cen64-qt?

### ISSUE THREAD

**Issue by JordanLongstaff** [dh4/cen64-qt#10]
I have a SteelSeries 3GC controller that I want to use to play an N64 game, but when I go into "Settings > Configure > Controllers" I do not see any way to assign button mappings for a controller.

I tried attaching a Controller Pak file and it didn't work. Is there something I'm missing there?

**Comment by dh4** [comment]
CEN64 doesn't yet have the capability to map buttons. It's keyboard only currently unless I've missed something.

If you're wanting an emulator that's currently stable enough to play games, I'd suggest Mupen64Plus.
