### ISSUE TITLE
Add right click options

### ISSUE THREAD

**Issue by ignacionelson** [dh4/cen64-qt#6]
Not an issue, but it would be great if right-clicking a game could open a menu with the options to:
- download/update info
- delete current info

Also, after deleting the current info of a ROM, it get's deselected so you need to click it again before trying to update the info. Keeping it on focus would be great.

Thanks for this beautiful frontend!

**Comment by dh4** [comment]
Both of these are good ideas and should have been implemented long ago. Added the right-click menu. 

I'll work on re-selecting the current ROM after configuration updates when I get a chance.

**Comment by dh4** [comment]
ROMs should be re-selected now: https://github.com/dh4/cen64-qt/commit/6e3cef60116914f676faa2fa7e0adc3837d9c672

**Comment by ignacionelson** [comment]
Thanks for doing these! Can you release it compiled please?

**Comment by dh4** [comment]
No problem! They fit in nicely with some other changes I was wanting to make.

See here for automatic builds of the latest commit:
https://github.com/dh4/cen64-qt#development-builds
