### ISSUE TITLE
Automatic number of columns on grid view?

### ISSUE THREAD

**Issue by ignacionelson** [dh4/cen64-qt#7]
As the size of each game box seems to be fixed, would it be possible to divide the width of screen size and the games width to make it show a dynamic amount of columns?

**Comment by dh4** [comment]
This was originally how I had planned to code it, however I decided on the way it's set up currently. I figure there are very few users who are constantly resizing their windows, so giving them a static column count gives them more fine-tuned control (say they want the grid to not take up the entire window, but have margins on the sides. They can do this easily).

**Comment by dh4** [comment]
Latest commit is the best of both worlds. Added a checkbox you can check to automatically update the grid, or uncheck to adjust column count manually.

**Comment by ignacionelson** [comment]
Oh, nice, thanks!
