### ISSUE TITLE
Cen64-Qt for Mac bug ? Maybe Windows too, I don't know.

### ISSUE THREAD

**Issue by spotanjo3** [dh4/cen64-qt#8]
I am a Mac user. I opened cen64-Qt and go to preferences>ROM Directories and find rom files in ROM folder. And it didn't showing up on cen64-Qt's list so I have to click OPEN ROM and find it and it's running ok. Why are ROMS not on cen64-Qt list ?

**Comment by dh4** [comment]
What are the extensions on your ROM files? It will only search for .z64, .n64, and those extensions within .zip files. It also performs a check on the ROM header to make sure the ROM is in Z64 format.

**Comment by spotanjo3** [comment]
Hi! Yes, I have .z64 unzip and .z64 zip, both. They runs but they don't showing up on the QT list. I put them in "ROMS" folder.. ROMS is CAPITAL. I try small letter.. "roms" and same thing. No roms showing up on the QT list but they works when I have to click OPEN ROM and find it and it is still running ok. No list on QT anyway. :( 

By the way, I use the latest version of XQuartz  if you must know.

**Comment by dh4** [comment]
I'm not able to reproduce this. It loads .z64 files fine on a Mac machine. Did you not change the view with View->Layout by chance?

Could you open up one of your .z64 files with a hex editor (like this one: https://github.com/ridiculousfish/HexFiend/) and make sure the first 4 bytes appear as:
80 37 12 40

**Comment by spotanjo3** [comment]
No hex need...

Oh no wonder... View -> Layout works. I changed it to Grid and I got those question mark box with rom's name. It works but Is there a way I can see the roms in art boxes instead of question mark box for QT ?

**Comment by dh4** [comment]
Check "Download Game Information" under Other in the settings. You'll get better information results if you set the ROM catalog to a mupen64plus.ini file from mupen64plus before doing this.
