### ISSUE TITLE
Can't load .n64 files

### ISSUE THREAD

**Issue by JordanLongstaff** [dh4/cen64-qt#9]
Even though the file chooser for ROMs says it allows .n64 files, when I try to open one it says it's "Not a valid .z64 file". This is because the endianness of a .n64 file is different from a .z64 file, which is not accounted for in your code. Please do so ASAP.

**Comment by dh4** [comment]
The latest commit allows conversion of little-endian ROMs using the converter under File->Convert V64/n64...

You can test it using the development builds:
https://github.com/dh4/cen64-qt#development-builds

Let me know if you have any issues using it.
